-- Users table (Extends Supabase auth automatically)
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text,
  plan text default 'free' check (plan in ('free', 'indie', 'pro', 'agency')),
  submission_count integer default 0,
  created_at timestamp with time zone default timezone('utc', now())
);

-- Projects table
create table public.projects (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  name text not null,
  website text not null,
  tagline text,
  description text,
  category text,
  pricing_model text,
  logo_url text,
  screenshots text[],
  founder_name text,
  twitter text,
  email text,
  status text default 'draft' check (status in ('draft', 'launching', 'launched')),
  created_at timestamp with time zone default timezone('utc', now())
);

-- Launch content (Generated by AI)
create table public.launch_content (
  id uuid default gen_random_uuid() primary key,
  project_id uuid references public.projects(id) on delete cascade,
  tagline text,
  short_pitch text,
  long_pitch text,
  tags text[],
  product_hunt_description text,
  reddit_post text,
  hn_post text,
  twitter_thread text,
  created_at timestamp with time zone default timezone('utc', now())
);

-- Platforms table (100+ sites)
create table public.platforms (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  website text,
  submit_url text,
  category text check (category in ('launch', 'ai_directory', 'saas_directory', 'review', 'community', 'deal')),
  automation_type text check (automation_type in ('api', 'form', 'email', 'manual')),
  automation_difficulty text check (automation_difficulty in ('easy', 'medium', 'hard', 'manual')),
  login_required boolean default false,
  priority text check (priority in ('tier_1', 'tier_2', 'tier_3')),
  is_active boolean default true,
  seo_value integer default 5,
  notes text
);

-- Submissions table
create table public.submissions (
  id uuid default gen_random_uuid() primary key,
  project_id uuid references public.projects(id) on delete cascade,
  platform_id uuid references public.platforms(id),
  status text default 'pending' check (status in ('pending', 'queued', 'submitted', 'approved', 'rejected', 'failed')),
  submitted_at timestamp with time zone,
  result_url text,
  error_message text,
  created_at timestamp with time zone default timezone('utc', now())
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.launch_content enable row level security;
alter table public.submissions enable row level security;
alter table public.platforms enable row level security;

-- Row Level Security (RLS) policies
create policy "Users can view own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

create policy "Users can view own projects" on public.projects for select using (auth.uid() = user_id);
create policy "Users can create own projects" on public.projects for insert with check (auth.uid() = user_id);
create policy "Users can update own projects" on public.projects for update using (auth.uid() = user_id);
create policy "Users can delete own projects" on public.projects for delete using (auth.uid() = user_id);

create policy "Users can view own submissions" on public.submissions for select using (
  project_id in (select id from public.projects where user_id = auth.uid())
);

-- Platforms are public for reading
create policy "Platforms are public" on public.platforms for select using (true);
